# Build command
# npm run build -- contents::iosevka-recursive-term
# https://typeof.net/Iosevka/customizer

[buildPlans.iosevka-recursive-term]
family = "Iosevka Recursive Term"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka-recursive-term.variants]
  inherits = "ss17"

    [buildPlans.iosevka-recursive-term.variants.design]
    capital-a = "straight-top-serifed"
    capital-b = "more-asymmetric-interrupted-unilateral-serifed"
    capital-c = "unilateral-inward-serifed"
    capital-d = "more-rounded-unilateral-serifed"
    capital-e = "top-left-serifed"
    capital-f = "top-left-serifed"
    capital-g = "toothless-corner-inward-serifed-hooked"
    capital-h = "top-left-serifed"
    capital-i = "short-serifed"
    capital-j = "descending-serifless"
    capital-k = "straight-bottom-right-serifed"
    capital-l = "motion-serifed"
    capital-m = "slanted-sides-flat-bottom-motion-serifed"
    capital-n = "asymmetric-serifless"
    capital-p = "open-motion-serifed"
    capital-q = "detached-tailed"
    capital-r = "standing-open-motion-serifed"
    capital-s = "serifless"
    capital-t = "motion-serifed"
    capital-u = "toothless-rounded-bilateral-motion-serifed"
    capital-v = "straight-motion-serifed"
    capital-w = "straight-vertical-sides-motion-serifed"
    capital-x = "curly-motion-serifed"
    capital-y = "straight-motion-serifed"
    capital-z = "straight-serifless"
    a = "single-storey-earless-rounded-serifed"
    b = "toothless-rounded-serifless"
    c = "serifless"
    d = "toothless-corner-serifless"
    e = "rounded"
    f = "extended-crossbar-at-x-height"
    g = "double-storey-open"
    h = "tailed-serifless"
    i = "serifless"
    j = "diagonal-tailed-serifless"
    k = "diagonal-tailed-cursive-serifless"
    l = "flat-tailed"
    m = "earless-single-arch-short-leg-tailed-serifless"
    n = "earless-corner-tailed-serifless"
    p = "earless-rounded-serifless"
    q = "earless-rounded-tailed-serifless"
    r = "corner-hooked-top-serifed"
    s = "serifless"
    t = "bent-hook-asymmetric-short-neck2"
    u = "toothless-rounded-motion-serifed"
    v = "cursive-serifless"
    w = "cursive-serifless"
    x = "cursive"
    y = "straight-serifless"
    z = "straight-serifless"
    eszet = "traditional-serifless"
    lower-pi = "small-capital"
    lower-chi = "curly-serifed"
    cyrl-en = "tailed-top-left-serifed"
    zero = "top-right-cutout"
    one = "no-base-long-top-serif"
    two = "straight-neck"
    three = "two-arcs"
    four = "closed-non-crossing"
    five = "vertical-upper-left-bar"
    six = "straight-bar"
    seven = "straight-serifless"
    eight = "two-circles"
    nine = "straight-bar"
    tilde = "low"
    asterisk = "hex-low"
    underscore = "low"
    caret = "high"
    paren = "normal"
    guillemet = "straight"
    number-sign = "slanted-open"
    ampersand = "flat-top"
    at = "compact"
    percent = "rings-continuous-slash-also-connected"
    bar = "force-upright"
    ascii-single-quote = "straight"
    question = "corner"
    pilcrow = "low"
    lig-ltgteq = "flat"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "with-notch"
    lig-double-arrow-bar = "with-notch"
    lig-single-arrow-bar = "with-notch"

  [buildPlans.iosevka-recursive-term.ligations]
  inherits = "javascript"
